
import { jsPDF } from 'jspdf';
import autoTable, { UserOptions } from 'jspdf-autotable';
import moment from 'moment';

// Logo URL from log.tsx
const BACKGROUND_IMAGE_URL = 'https://raw.githubusercontent.com/Naveen06-A/image-/451d7ca2516e5ab3862be90d6f5b448d48ade876/red-tulip-logo.jpg';
// Fallback base64 image (placeholder; replace with actual base64 to avoid CORS issues)
// const BACKGROUND_IMAGE_BASE64 = 'data:image/jpeg;base64,/9j/4AAQSkZJRgABAQE...'; // Replace with actual base64 string

interface GeneratePdfOptions {
  title: string;
  head: string[][];
  body: (string | number)[][];
  fileName: string;
  outputType: 'blob' | 'datauristring';
}

export const generatePdf = async ({ title, head, body, fileName, outputType }: GeneratePdfOptions) => {
  try {
    // Validate input
    if (!head || !head[0] || head[0].length === 0 || !body || !Array.isArray(body)) {
      console.error('Invalid head or body:', { head, bodyLength: body?.length });
      throw new Error('Invalid head or body data for PDF generation');
    }

    const doc = new jsPDF({
      orientation: 'landscape',
      unit: 'mm',
      format: 'a4',
    });

    // Set document properties
    doc.setProperties({
      title,
      creator: 'RedTulip Property Management',
      author: 'RedTulip',
    });

    // Add white background rectangle for cover page text readability
    doc.setFillColor(255, 255, 255);
    doc.rect(50, 60, 197, 60, 'F'); // White rectangle behind cover text

    // Set opacity for background image on cover page (darker)
    doc.setGState(new doc.GState({ opacity: 0.3 }));

    // Add logo centered on cover page (100mm x 100mm)
    try {
      console.log('Attempting to load logo for cover page:', BACKGROUND_IMAGE_URL);
      doc.addImage(BACKGROUND_IMAGE_URL, 'JPEG', (297 - 100) / 2, (210 - 100) / 2, 100, 100, undefined, 'NONE');
    } catch (err) {
      console.warn('Failed to load logo URL on cover page:', err);
      // Uncomment and replace with actual base64 if CORS issue occurs
      // doc.addImage(BACKGROUND_IMAGE_BASE64, 'JPEG', (297 - 100) / 2, (210 - 100) / 2, 100, 100, undefined, 'NONE');
    }

    // Reset opacity for text
    doc.setGState(new doc.GState({ opacity: 1 }));

    // Add cover page content
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(24);
    doc.setTextColor(31, 41, 55); // Dark gray
    doc.text('Property Report', 148.5, 80, { align: 'center' });
    doc.setFontSize(14);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(107, 114, 128); // Gray
    doc.text('Generated by RedTulip Property Management', 148.5, 95, { align: 'center' });
    doc.text(`Date: ${moment().format('MMMM Do, YYYY')}`, 148.5, 105, { align: 'center' });
    doc.addPage();

    // Set fonts for content pages
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(12);

    // Add header on content pages
    const addHeader = () => {
      doc.setFontSize(14);
      doc.setTextColor(31, 41, 55);
      doc.text(title, 14, 15);
      doc.setFontSize(10);
      doc.setTextColor(107, 114, 128);
      doc.text(`Generated on: ${moment().format('MMMM Do YYYY, h:mm:ss a')}`, 14, 22);
      doc.text('RedTulip Property Management', 14, 28);
      doc.line(14, 30, 283, 30); // Horizontal line
    };

    // Define column widths (total 25 columns, optimized for A4 landscape)
    const columnWidths = [
      8,  // Street Number
      18, // Street Name
      18, // Suburb
      8,  // Postcode
      12, // Agent
      12, // Type
      12, // Price
      12, // Sold Price
      8,  // Status
      8,  // Commission (%)
      12, // Commission Earned
      12, // Agency
      12, // Expected Price
      8,  // Sale Type
      8,  // Bedrooms
      8,  // Bathrooms
      8,  // Car Garage
      8,  // SQM
      8,  // Land Size
      12, // Listed Date
      12, // Sold Date
      8,  // Flood Risk
      8,  // Bushfire Risk
      8,  // Contract Status
      20, // Features
    ];

    // Normalize column widths
    const totalWidth = 297 - 28; // A4 landscape width (297mm) - 14mm margins
    const totalDefinedWidth = columnWidths.reduce((sum, width) => sum + width, 0);
    const normalizedWidths = columnWidths.map((width) => (width / totalDefinedWidth) * totalWidth);

    // Configure autoTable
    autoTable(doc, {
      head,
      body,
      startY: 35,
      margin: { top: 35, left: 14, right: 14, bottom: 20 },
      styles: {
        font: 'helvetica',
        fontSize: 7,
        cellPadding: 1.5,
        overflow: 'linebreak',
        minCellHeight: 5,
        halign: 'left',
        valign: 'middle',
        textColor: [55, 65, 81], // Dark gray text
        fillColor: [255, 255, 255], // White background for readability
      },
      headStyles: {
        fillColor: [59, 130, 246], // Blue
        textColor: [255, 255, 255],
        fontSize: 7,
        fontStyle: 'bold',
        halign: 'center',
      },
      alternateRowStyles: {
        fillColor: [243, 244, 246], // Light gray for alternate rows
      },
      columnStyles: head[0].reduce((acc: { [key: number]: Partial<UserOptions> }, _, index) => {
        acc[index] = { cellWidth: normalizedWidths[index] };
        return acc;
      }, {}),
      didDrawPage: (data) => {
        // Set opacity for background image on content pages (lighter)
        doc.setGState(new doc.GState({ opacity: 0.1 }));
        // Add logo centered on content pages (100mm x 100mm)
        try {
          console.log('Attempting to load logo for content page:', BACKGROUND_IMAGE_URL);
          doc.addImage(BACKGROUND_IMAGE_URL, 'JPEG', (297 - 100) / 2, (210 - 100) / 2, 100, 100, undefined, 'NONE');
        } catch (err) {
          console.warn('Failed to load logo URL on content page:', err);
          // Uncomment and replace with actual base64 if CORS issue occurs
          // doc.addImage(BACKGROUND_IMAGE_BASE64, 'JPEG', (297 - 100) / 2, (210 - 100) / 2, 100, 100, undefined, 'NONE');
        }
        doc.setGState(new doc.GState({ opacity: 1 }));

        // Add header and footer
        addHeader();
        doc.setFontSize(8);
        doc.setTextColor(107, 114, 128);
        doc.text('RedTulip Property Management - Confidential Report', 14, doc.internal.pageSize.height - 10);
        doc.text(`Page ${data.pageNumber} of ${doc.getNumberOfPages()}`, 283, doc.internal.pageSize.height - 10, { align: 'right' });
      },
      theme: 'plain',
    });

    // Ensure at least one page has content
    if (doc.getNumberOfPages() === 1) {
      doc.addPage();
      doc.setGState(new doc.GState({ opacity: 0.1 }));
      try {
        console.log('Attempting to load logo for empty page:', BACKGROUND_IMAGE_URL);
        doc.addImage(BACKGROUND_IMAGE_URL, 'JPEG', (297 - 100) / 2, (210 - 100) / 2, 100, 100, undefined, 'NONE');
      } catch (err) {
        console.warn('Failed to load logo URL on empty page:', err);
        // Uncomment and replace with actual base64 if CORS issue occurs
        // doc.addImage(BACKGROUND_IMAGE_BASE64, 'JPEG', (297 - 100) / 2, (210 - 100) / 2, 100, 100, undefined, 'NONE');
      }
      doc.setGState(new doc.GState({ opacity: 1 }));
      addHeader();
    }

    // Update page numbers
    const pageCount = doc.getNumberOfPages();
    for (let i = 2; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setFontSize(8);
      doc.setTextColor(107, 114, 128);
      doc.text(`Page ${i - 1} of ${pageCount - 1}`, 283, doc.internal.pageSize.height - 10, { align: 'right' });
    }

    // Output based on type
    if (outputType === 'blob') {
      const blob = doc.output('blob');
      console.log('PDF Blob generated, size:', blob.size);
      return blob;
    } else if (outputType === 'datauristring') {
      const dataUri = doc.output('datauristring');
      console.log('PDF Data URI generated, length:', dataUri.length);
      if (!dataUri.startsWith('data:application/pdf;')) {
        throw new Error('Generated PDF data URI is invalid');
      }
      return dataUri;
    } else {
      throw new Error('Invalid output type');
    }
  } catch (err) {
    console.error('PDF generation error:', err);
    throw err;
  }
};
